[Splunk_TA_censys_checkpointer]
field.state = string

[asm_risk_instances_seed]
enforceTypes = false
field.ip = string
field.seed = string
accelerated_fields.ip_accel = {"ip": 1}

[asm_logbook_ip_to_seed]
enforceTypes = false
field.ip = string
field.seed = string
accelerated_fields.ip_accel = {"ip": 1}
